routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'register' => false,
]);

Route::get('/home', function () {
    return redirect('/');
});
Route::post('/login-only-with-password', 'Auth\LoginController@loginOnlyWithPassword')->middleware('guest');

Route::get('/control', 'Auth\ControlModeController@showControlPage')->name('control');
Route::get('/unset-control', 'Auth\ControlModeController@unsetControlMode')->name('unset-control');
Route::post('/set-control', 'Auth\ControlModeController@setControlMode')->name('set-control');

Route::middleware(['auth', 'locale'])->group(function () {
    // --- Clients
    Route::get('/api/clients', 'Api\ClientController@list');
    Route::post('/api/clients', 'Api\ClientController@list');
    Route::get('/clients/debts', 'ClientController@debts')->name('clients.debts');
    Route::resource('clients', 'ClientController');
    Route::get('/clients/{id}/payments', 'ClientController@payments')->name('clients.payments');

    // --- Invoices
    // TODO: should refactor
    Route::get('/api/invoices', 'Api\InvoiceController@list');
    Route::get('/api/invoices/{id}', 'Api\InvoiceController@show');
    Route::get('/api/invoices/{id}/invoice-products', 'Api\InvoiceProductController@getInvoiceProductsByInvoiceId');
    Route::resource('invoices', 'InvoiceController');
    Route::get('/api/invoices/{invoice}/download', 'Api\InvoiceController@download')->name('api.invoices.download');

    // --- Payments
    Route::post('/api/payments/store', 'Api\PaymentController@store');
    Route::delete('/api/payments/{id}', 'Api\PaymentController@destroy');
    Route::resource('payments', 'PaymentController');

    // --- Supplier Invoices
    Route::get('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@show');
    Route::post('/api/supplier-invoices/store', 'Api\SupplierInvoiceController@store');
    Route::patch('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@update');
    Route::delete('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@destroy');
    Route::get('/supplier-invoices{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Products
    Route::resource('products', 'ProductController')->names('products');
    Route::prefix('api')->name('api.')->group(function () {
        Route::prefix('products')->name('products.')->group(function () {
            Route::get('/', 'Api\ProductController@list')->name('list');
            // TODO: should refactor to /invoice-prices
            Route::get('/prices', 'Api\ProductController@getProductsWithInvoicePrices')->name('get-products-with-invoice-prices');
            Route::get('/supply-prices', 'Api\ProductController@getProductsWithSupplyPrices')->name('get-products-with-supply-prices');
            // TODO: should refactor
            Route::get('/barcodes', 'Api\ProductController@getAllWithBarcode')->name('barcodes');
        });
    });

    // --- Client Price lists
    Route::prefix('api')->name('api.')->group(function () {
        Route::get('/client-pricelists', 'Api\ClientPricelistController@list')->name('client-pricelist.index');
        Route::get('/client-pricelists/{id}', 'Api\ClientPricelistController@show')->name('client-pricelist.show');
        Route::post('/client-pricelists/{pricelist}/duplicate', 'Api\ClientPricelistController@duplicate')->name('client-pricelist.duplicate');
        Route::delete('/client-pricelists/{id}', 'Api\ClientPricelistController@destroy')->name('client-pricelist.destroy');
    });
    Route::resource('client-pricelists', 'ClientPricelistController');
    Route::get('/client-pricelists', function () {
        return view('default');
    })->where('all', '.*')->name('client-pricelists.index');
    Route::get('/client-pricelists/{id}/duplicate', function () {
        return view('default');
    })->where('all', '.*');

    // --- Supplier Price lists
    Route::get('/api/supplier-pricelists', 'Api\SupplierPricelistController@list');
    Route::delete('/api/supplier-pricelists/{id}', 'Api\SupplierPricelistController@destroy');
    Route::resource('supplier-pricelists', 'SupplierPricelistController');

    // --- Reports
    Route::get('/api/reports/by-client-payments', 'Api\ReportController@byPayments');
    Route::post('/api/reports/by-products', 'Api\ReportController@byProducts');
    Route::post('/api/reports/products-moving', 'Api\ReportController@productsMoving')->middleware('control-mode');
    Route::get('/api/reports/revision-by-suppliers', 'Api\ReportController@revisionBySuppliers')->middleware('control-mode');
    Route::get('/api/reports/by-supplies', 'Api\ReportController@bySupplies')->middleware('control-mode');
    Route::get('/reports/by-products', function () {
        return view('reports.by-products');
    })->name('reports.by-products');
    Route::get('/reports/products-moving', function () {
        return view('reports.products-moving');
    })->middleware('control-mode')->name('reports.products-moving');
    Route::get('/reports/by-client-payments', function () {
        return view('default');
    })->name('reports.by-payments');
    Route::get('/reports/revision-by-suppliers', function () {
        return view('default');
    })->middleware('control-mode')->name('reports.by-suppliers');
    Route::get('/reports/by-supplies', function () {
        return view('default');
    })->middleware('control-mode')->name('reports.by-supplies');

    // --- Revisions
    Route::post('/api/revision/get-supplies-and-invoices', 'Api\RevisionController@getSuppliesAndInvoices')->middleware('control-mode');
    Route::get('/revisions', 'RevisionController@index')->middleware(['locale', 'control-mode'])->name('revisions');
    //Route::get('/stocktaking', 'RevisionController@stocktaking')->middleware('locale');

    // --- Suppliers
    Route::get('/api/suppliers', 'Api\SupplierController@index');
    Route::post('/api/suppliers', 'Api\SupplierController@store');
    Route::get('/api/suppliers/{id}', 'Api\SupplierController@show');
    Route::patch('/api/suppliers/{id}', 'Api\SupplierController@update');
    Route::delete('/api/suppliers/{id}', 'Api\SupplierController@destroy');
    Route::get('/suppliers{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Supplies
    Route::post('/api/supplies', 'Api\SupplyController@store');
    Route::get('/api/supplies/{id}', 'Api\SupplyController@show');
    // patch не работает с form-data в laravel
    Route::post('/api/supplies/{id}', 'Api\SupplyController@update');
    Route::delete('/api/supplies/{id}', 'Api\SupplyController@destroy');
    Route::get('/api/supplies/{id}/supply-products', 'Api\SupplyProductController@getSupplyProductsBySupplyId');
    Route::get('/supplies{all}', function () {
        return view('default');
    })->where('all', '.*');
//    Route::apiResource('activity', 'Api\ActivityController')->names('activity');

    // --- Orders
    Route::prefix('api')->name('api.')->group(function () {
        Route::apiResource('orders', 'Api\OrderController')->names('order');
    });
    Route::get('/orders', function () {
        return view('default');
    })->name('orders.index');
    Route::get('/orders{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Logs
    Route::get('/logs/login', function () {
        return view('default');
    })->middleware('control-mode')->name('logs.login');

    // --- Settings
    Route::prefix('settings')
        ->name('settings.')
        ->middleware('control-mode')
        ->group(function () {
            Route::get('/', 'SettingsController@index')->name('index');
            Route::get('/euro-price/edit', function () {
                return view('default');
            })->name('euro-price.edit');
        });
    Route::prefix('api/settings')
         ->name('api.settings.')
         ->middleware('control-mode')
         ->group(function () {
             Route::get('/', 'Api\SettingController@index')->name('index');
             Route::post('/', 'Api\SettingController@store')->name('store');
             Route::patch('/', 'Api\SettingController@update')->name('update');
             Route::delete('/', 'Api\SettingController@destroy')->name('destroy');
         });
});

Route::apiResource('/api/activity', 'Api\ActivityController')->names('activity');

//Route::resource('supplies', 'SupplyController');

Route::permanentRedirect('/', \App\Models\User::HOME_URL);

//Route::get('/', 'RevisioController@index')->middleware('locale');

app/Models/SupplierPricelist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\SupplierPricelist
 *
 * @property int $id
 * @property string $name
 * @property bool $assigned_to_euro
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Client[] $clients
 * @property-read int|null $clients_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SupplierPricelistProductPrice[] $productPrices
 * @property-read int|null $product_prices_count
 * @method static \Illuminate\Database\Eloquent\Builder|SupplierPricelist dollarAssigned()
 * @method static \Database\Factories\SupplierPricelistFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|SupplierPricelist newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|SupplierPricelist newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|SupplierPricelist query()
 * @method static \Illuminate\Database\Eloquent\Builder|SupplierPricelist whereAssignedToEuro($value)
 * @method static \Illuminate\Database\Eloquent\Builder|SupplierPricelist whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|SupplierPricelist whereName($value)
 * @mixin \Eloquent
 */
class SupplierPricelist extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = ['name', 'assigned_to_euro'];

    protected $casts = [
        'assigned_to_euro' => 'bool',
    ];

    public function clients()
    {
        return $this->hasMany(Client::class);
    }

    public function productPrices()
    {
        return $this->hasMany(SupplierPricelistProductPrice::class);
    }

    public function scopeDollarAssigned($query)
    {
        return $query->where('assigned_to_euro', true);
    }
}

app/Http/Controllers/Api/SupplierPricelistController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Resources\PricelistResource;
use App\Models\SupplierPricelist;

class SupplierPricelistController extends \App\Http\Controllers\Controller
{
    public function list()
    {
        $pricelists = SupplierPricelist::all();
        return PricelistResource::collection($pricelists);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pricelist = SupplierPricelist::find($id);
        $success = $pricelist->delete();

        return [
            'success' => $success,
        ];
    }
}

app/Http/Controllers/SupplierPricelistController.php
<?php

namespace App\Http\Controllers;

use App\Models\SupplierPricelist;
use App\Models\SupplierPricelistProductPrice;
use Illuminate\Http\Request;

class SupplierPricelistController extends Controller
{
    const PRICELIST__RECORDS_PER_PAGE = 100;

    public function __construct()
    {
        $this->middleware(['auth', 'locale']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('supplierPricelists.index')
            ->with('i', (request()->input('page', 1) - 1) * self::PRICELIST__RECORDS_PER_PAGE);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('supplierPricelists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required'
        ]);

        // fix: assign `assigned_to_euro` to bool
        $request->merge([
            'assigned_to_euro' => $request->assigned_to_euro === 'on',
        ]);

        $pricelist = SupplierPricelist::create($request->all());

        return redirect()->route('supplier-pricelists.index')
            ->with('success', "Прайс-лист поставщика \"{$pricelist->name}\" создан");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pricelist = SupplierPricelist::find($id);

        if ($pricelist === null) {
            abort(404, 'Прайслист для поставщиков не найден');
        }

        $currentDate = date('d.m.Y');
        $ORDER = 'ASC';

        $productPrices = SupplierPricelistProductPrice::join('products', 'supplier_pricelist_product_prices.product_id', '=', 'products.id')
            ->select('supplier_pricelist_product_prices.*')
            ->where('supplier_pricelist_id', $id)
            ->orderBy('products.name', $ORDER)
            ->get();

        return view('supplierPricelists.show', compact(['currentDate', 'pricelist', 'productPrices']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pricelist = SupplierPricelist::find($id);
        return view('supplierPricelists.edit', compact(['pricelist']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'name'  => 'required'
        ]);

        $pricelist = SupplierPricelist::find($id);
        $pricelist->assigned_to_euro = (boolean)$request->get('assigned_to_euro');
        $pricelist->name = $request->get('name');
        $pricelist->save();

        return redirect()->route('supplier-pricelists.index')
            // TODO: указать текст сообщения
            ->with('success', "Прайс-лист поставщика \"{$pricelist->name}\" обновлен");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pricelist     = SupplierPricelist::find($id);
        $pricelistName = $pricelist->name;
        $pricelist->delete();

        return redirect()->route('supplier-pricelists.index')
            ->with('success', "Прайс-лист поставщика \"{$pricelistName}\" удален");
    }
}

resources/views/supplierPricelists/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Создание прайс-листа поставщика</h2>
      </div>
      <p class="pull-right">
        <a class="btn btn-primary" href="{{ route('supplier-pricelists.index') }}">Назад</a>
      </p>
    </div>
  </div>

  @if (count($errors) > 0)
    <div class="alert alert-danger">
      <strong>Ошибка!</strong><br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  {!! Form::open(['route' => 'supplier-pricelists.store', 'method' => 'POST']) !!}
    @include('supplierPricelists.form')
  {!! Form::close() !!}
@endsection

resources/views/supplierPricelists/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Редактирование прайс-листа поставщика</h2>
      </div>
      <p class="pull-right">
        <a class="btn btn-primary" href="{{ route('supplier-pricelists.index') }}">Назад</a>
      </p>
    </div>
  </div>

  @if (count($errors) > 0)
    <div class="alert alert-danger">
      <strong>Ошибка!</strong><br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  {!! Form::model($pricelist, ['method' => 'PATCH', 'route' => ['supplier-pricelists.update', $pricelist->id]]) !!}
    @include('supplierPricelists.form')
  {!! Form::close() !!}
@endsection

resources/views/supplierPricelists/form.blade.php
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <strong>Название:</strong>
      {!! Form::text('name', null, ['placeholder' => '', 'class' => 'form-control']) !!}
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <strong>Курс евро:</strong>
      <toggle-button
        name="assigned_to_euro"
        :value="{{ isset($pricelist) && $pricelist->assigned_to_euro ? 'true' : 'false' }}"
      />
    </div>
  </div>
</div>

<div class="col-md-12 text-center">
  <button type="submit" class="btn btn-primary">Сохранить</button>
</div>

resources/views/supplierPricelists/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Прайс-листы поставщиков</h2>
      </div>
      <p class="pull-right">
        <a class="btn btn-success" href="{{ route('supplier-pricelists.create') }}">Добавить прайс-лист поставщика</a>
      </p>
    </div>
  </div>

  @if ($message = Session::get('success'))
    <div class="alert alert-success">
      <p>{{ $message }}</p>
    </div>
  @endif

  <supplier-pricelists />
@endsection

resources/views/supplierPricelists/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Прайс-лист поставщика "{{ $pricelist->name }}"</h2>
        <p>от {{ $currentDate }}</p>
      </div>
      <p class="pull-right">
        <a class="btn btn-primary" href="{{ route('supplier-pricelists.index') }}">Назад</a>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <tbody>
          @foreach ($productPrices as $i => $productPrice)
            @if ($productPrice->price != 0)
              <tr>
                <td>{{ ($i + 1)  }}</td>
                <td>{{ $productPrice->product->name }}</td>
                <td>{{ fineNumber($productPrice->price, true) }} руб.</td>
              </tr>
            @endif
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection