routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'register' => false,
]);

Route::get('/home', function () {
    return redirect('/');
});
Route::post('/login-only-with-password', 'Auth\LoginController@loginOnlyWithPassword')->middleware('guest');

Route::get('/control', 'Auth\ControlModeController@showControlPage')->name('control');
Route::get('/unset-control', 'Auth\ControlModeController@unsetControlMode')->name('unset-control');
Route::post('/set-control', 'Auth\ControlModeController@setControlMode')->name('set-control');

Route::middleware(['auth', 'locale'])->group(function () {
    // --- Clients
    Route::get('/api/clients', 'Api\ClientController@list');
    Route::post('/api/clients', 'Api\ClientController@list');
    Route::get('/clients/debts', 'ClientController@debts')->name('clients.debts');
    Route::resource('clients', 'ClientController');
    Route::get('/clients/{id}/payments', 'ClientController@payments')->name('clients.payments');

    // --- Invoices
    // TODO: should refactor
    Route::get('/api/invoices', 'Api\InvoiceController@list');
    Route::get('/api/invoices/{id}', 'Api\InvoiceController@show');
    Route::get('/api/invoices/{id}/invoice-products', 'Api\InvoiceProductController@getInvoiceProductsByInvoiceId');
    Route::resource('invoices', 'InvoiceController');
    Route::get('/api/invoices/{invoice}/download', 'Api\InvoiceController@download')->name('api.invoices.download');

    // --- Payments
    Route::post('/api/payments/store', 'Api\PaymentController@store');
    Route::delete('/api/payments/{id}', 'Api\PaymentController@destroy');
    Route::resource('payments', 'PaymentController');

    // --- Supplier Invoices
    Route::get('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@show');
    Route::post('/api/supplier-invoices/store', 'Api\SupplierInvoiceController@store');
    Route::patch('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@update');
    Route::delete('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@destroy');
    Route::get('/supplier-invoices{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Products
    Route::resource('products', 'ProductController')->names('products');
    Route::prefix('api')->name('api.')->group(function () {
        Route::prefix('products')->name('products.')->group(function () {
            Route::get('/', 'Api\ProductController@list')->name('list');
            // TODO: should refactor to /invoice-prices
            Route::get('/prices', 'Api\ProductController@getProductsWithInvoicePrices')->name('get-products-with-invoice-prices');
            Route::get('/supply-prices', 'Api\ProductController@getProductsWithSupplyPrices')->name('get-products-with-supply-prices');
            // TODO: should refactor
            Route::get('/barcodes', 'Api\ProductController@getAllWithBarcode')->name('barcodes');
        });
    });

    // --- Client Price lists
    Route::prefix('api')->name('api.')->group(function () {
        Route::get('/client-pricelists', 'Api\ClientPricelistController@list')->name('client-pricelist.index');
        Route::get('/client-pricelists/{id}', 'Api\ClientPricelistController@show')->name('client-pricelist.show');
        Route::post('/client-pricelists/{pricelist}/duplicate', 'Api\ClientPricelistController@duplicate')->name('client-pricelist.duplicate');
        Route::delete('/client-pricelists/{id}', 'Api\ClientPricelistController@destroy')->name('client-pricelist.destroy');
    });
    Route::resource('client-pricelists', 'ClientPricelistController');
    Route::get('/client-pricelists', function () {
        return view('default');
    })->where('all', '.*')->name('client-pricelists.index');
    Route::get('/client-pricelists/{id}/duplicate', function () {
        return view('default');
    })->where('all', '.*');

    // --- Supplier Price lists
    Route::get('/api/supplier-pricelists', 'Api\SupplierPricelistController@list');
    Route::delete('/api/supplier-pricelists/{id}', 'Api\SupplierPricelistController@destroy');
    Route::resource('supplier-pricelists', 'SupplierPricelistController');

    // --- Reports
    Route::get('/api/reports/by-client-payments', 'Api\ReportController@byPayments');
    Route::post('/api/reports/by-products', 'Api\ReportController@byProducts');
    Route::post('/api/reports/products-moving', 'Api\ReportController@productsMoving')->middleware('control-mode');
    Route::get('/api/reports/revision-by-suppliers', 'Api\ReportController@revisionBySuppliers')->middleware('control-mode');
    Route::get('/api/reports/by-supplies', 'Api\ReportController@bySupplies')->middleware('control-mode');
    Route::get('/reports/by-products', function () {
        return view('reports.by-products');
    })->name('reports.by-products');
    Route::get('/reports/products-moving', function () {
        return view('reports.products-moving');
    })->middleware('control-mode')->name('reports.products-moving');
    Route::get('/reports/by-client-payments', function () {
        return view('default');
    })->name('reports.by-payments');
    Route::get('/reports/revision-by-suppliers', function () {
        return view('default');
    })->middleware('control-mode')->name('reports.by-suppliers');
    Route::get('/reports/by-supplies', function () {
        return view('default');
    })->middleware('control-mode')->name('reports.by-supplies');

    // --- Revisions
    Route::post('/api/revision/get-supplies-and-invoices', 'Api\RevisionController@getSuppliesAndInvoices')->middleware('control-mode');
    Route::get('/revisions', 'RevisionController@index')->middleware(['locale', 'control-mode'])->name('revisions');
    //Route::get('/stocktaking', 'RevisionController@stocktaking')->middleware('locale');

    // --- Suppliers
    Route::get('/api/suppliers', 'Api\SupplierController@index');
    Route::post('/api/suppliers', 'Api\SupplierController@store');
    Route::get('/api/suppliers/{id}', 'Api\SupplierController@show');
    Route::patch('/api/suppliers/{id}', 'Api\SupplierController@update');
    Route::delete('/api/suppliers/{id}', 'Api\SupplierController@destroy');
    Route::get('/suppliers{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Supplies
    Route::post('/api/supplies', 'Api\SupplyController@store');
    Route::get('/api/supplies/{id}', 'Api\SupplyController@show');
    // patch не работает с form-data в laravel
    Route::post('/api/supplies/{id}', 'Api\SupplyController@update');
    Route::delete('/api/supplies/{id}', 'Api\SupplyController@destroy');
    Route::get('/api/supplies/{id}/supply-products', 'Api\SupplyProductController@getSupplyProductsBySupplyId');
    Route::get('/supplies{all}', function () {
        return view('default');
    })->where('all', '.*');
//    Route::apiResource('activity', 'Api\ActivityController')->names('activity');

    // --- Orders
    Route::prefix('api')->name('api.')->group(function () {
        Route::apiResource('orders', 'Api\OrderController')->names('order');
    });
    Route::get('/orders', function () {
        return view('default');
    })->name('orders.index');
    Route::get('/orders{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Logs
    Route::get('/logs/login', function () {
        return view('default');
    })->middleware('control-mode')->name('logs.login');

    // --- Settings
    Route::prefix('settings')
        ->name('settings.')
        ->middleware('control-mode')
        ->group(function () {
            Route::get('/', 'SettingsController@index')->name('index');
            Route::get('/euro-price/edit', function () {
                return view('default');
            })->name('euro-price.edit');
        });
    Route::prefix('api/settings')
         ->name('api.settings.')
         ->middleware('control-mode')
         ->group(function () {
             Route::get('/', 'Api\SettingController@index')->name('index');
             Route::post('/', 'Api\SettingController@store')->name('store');
             Route::patch('/', 'Api\SettingController@update')->name('update');
             Route::delete('/', 'Api\SettingController@destroy')->name('destroy');
         });
});

Route::apiResource('/api/activity', 'Api\ActivityController')->names('activity');

//Route::resource('supplies', 'SupplyController');

Route::permanentRedirect('/', \App\Models\User::HOME_URL);

//Route::get('/', 'RevisioController@index')->middleware('locale');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Client
 *
 * @property int $id
 * @property int|null $client_pricelist_id
 * @property string $name
 * @property string $phone
 * @property string $address
 * @property int $cashless
 * @property boolean $is_archived
 * @property-read mixed $debt
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Invoice[] $invoices
 * @property-read int|null $invoices_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Payment[] $payments
 * @property-read int|null $payments_count
 * @property-read \App\Models\ClientPricelist|null $pricelist
 * @method static \Database\Factories\ClientFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|Client newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Client newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Client query()
 * @method static \Illuminate\Database\Eloquent\Builder|Client whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Client whereCashless($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Client whereClientPricelistId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Client whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Client whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Client wherePhone($value)
 * @mixin \Eloquent
 */
class Client extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = ['client_pricelist_id', 'name', 'phone', 'address', 'cashless', 'is_archived'];

    public function invoices()
    {
        return $this->hasMany(Invoice::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    public function pricelist()
    {
        return $this->belongsTo(ClientPricelist::class, 'client_pricelist_id');
    }

    public function scopeIsNotArchived($query)
    {
        return $query->where('is_archived', 0);
    }

    public function getDebtAttribute()
    {
        $debt = 0;

        if ($this->invoices) {
            foreach ($this->invoices as $invoice) {
                $debt += $invoice->amount;
            }
        }

        if ($this->payments) {
            foreach ($this->payments as $payment) {
                $debt -= $payment->amount;
            }
        }

        return $debt;
    }
}

app/Http/Controllers/Api/ClientController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Resources\ClientResource;
use App\Models\Client;
use Illuminate\Http\Request;

class ClientController extends \App\Http\Controllers\Controller
{
    const PRODUCT__RECORDS_PER_PAGE = 10;

    public function list(Request $request)
    {
        $clientsQuery = Client::query()->orderBy('name', 'asc');

        if ($request->onlyNotArchived) {
            $clientsQuery = $clientsQuery->isNotArchived();
        }

        $clients = $clientsQuery->get();

        return ClientResource::collection($clients);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\ClientPricelist;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    const CLIENT__RECORDS_PER_PAGE = 1000;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('clients.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pricelists = ClientPricelist::pluck('name', 'id');

        return view('clients.create', compact(['pricelists']));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function debts()
    {
        return view('clients.debts');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'address' => 'required',
            'name'    => 'required',
            'phone'   => 'required'
        ]);

        $request->merge([
            'cashless'    => $request->has('cashless'),
            'is_archived' => $request->has('is_archived'),
        ]);

        $client = Client::create($request->all());

        return redirect()->route('clients.index')
            ->with('success', "Клиент \"{$client->name}\" создан");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = Client::find($id);
        return view('clients.show', compact('client'));
    }

    public function payments($id)
    {
        $client = Client::find($id);

        if (!$client) {
            // TODO: Добавить 2 языка
            abort(404, "Клиент не найден");
        }

        return view('clients.payments', compact('client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client     = Client::find($id);
        $pricelists = ClientPricelist::pluck('name', 'id');

        return view('clients.edit', compact(['client', 'pricelists']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'address' => 'required',
            'name'    => 'required',
            'phone'   => 'required'
        ]);

        $client = Client::find($id);
        $request->merge([
            'cashless'    => $request->has('cashless'),
            'is_archived' => $request->has('is_archived'),
        ]);

        $client->update($request->all());

        return redirect()->route('clients.index')
            ->with('success', "Клиент \"{$client->name}\" обновлен");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client     = Client::find($id);
        $clientName = $client->name;
        $client->delete();

        return redirect()->route('clients.index')
            ->with('success', "Клиент \"{$clientName}\" удален");
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Создание клиента</h2>
      </div>
      <p class="pull-right">
        <a class="btn btn-primary" href="{{ route('clients.index') }}">Назад</a>
      </p>
    </div>
  </div>

  @if (count($errors) > 0)
    <div class="alert alert-danger">
      <strong>Ошибка!</strong><br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  {!! Form::open(['route' => 'clients.store', 'method' => 'POST']) !!}
    @include('clients.form')
  {!! Form::close() !!}
@endsection

resources/views/clients/debts.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Долги по клиентам</h2>
      </div>
    </div>
  </div>

  @if ($message = Session::get('success'))
    <div class="alert alert-success">
      <p>{{ $message }}</p>
    </div>
  @endif

  <clients :debts="true"></clients>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="pull-left">
        <h2>Редактирование клиента</h2>
      </div>
      <p class="pull-right">
        <a class="btn btn-primary" href="{{ route('clients.index') }}">Назад</a>
      </p>
    </div>
  </div>

  @if (count($errors) > 0)
    <div class="alert alert-danger">
      <strong>Ошибка!</strong><br><br>
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
  @endif

  {!! Form::model($client, ['method' => 'PATCH', 'route' => ['clients.update', $client->id]]) !!}
    @include('clients.form')
  {!! Form::close() !!}
@endsection

resources/views/clients/form.blade.php
<div class="row">
  <div class="col-md-5">
    <div class="form-group">
      <strong>Имя</strong>
      {!! Form::text('name', null, ['placeholder' => '', 'class' => 'form-control']) !!}
    </div>
  </div>

  <div class="col-md-2">
    <div class="form-group">
      <strong>Телефон</strong>
      {!! Form::text('phone', null, ['placeholder' => '', 'class' => 'form-control']) !!}
    </div>
  </div>

  <div class="col-md-5">
    <div class="form-group">
      <strong>
        @if(isset($client) && $client->client_pricelist_id)
          <a
            href="/client-pricelists/{{ $client->client_pricelist_id }}"
          >Прайслист</a>
        @else
          Прайслист
        @endif
      </strong>
      {!! Form::select('client_pricelist_id', $pricelists, null, ['placeholder' => '', 'class' => 'form-control', 'required' => '']) !!}
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-5">
    <div class="form-group">
      <strong>Адрес</strong>
      {!! Form::text('address', null, ['placeholder' => '', 'class' => 'form-control']) !!}
    </div>
  </div>
  <div class="col-md-5">
    <div style="padding-top: 2rem" class="form-group d-flex">
      {!! Form::checkbox('cashless', null, null, [
          'style' => "height: 18px; width: 18px;",
          'id' => 'cashless-field',
        ]) !!}
      <label class="ml-2" for="cashless-field">
        <strong>Безналичный расчет</strong>
      </label>
    </div>
  </div>
  <div class="col-md-2">
    <div style="padding-top: 2rem" class="form-group d-flex">
      {!! Form::checkbox('is_archived', null, null, [
        'style' => "height: 18px; width: 18px;",
        'id' => 'is-archived-field',
      ]) !!}
      <label class="ml-2" for="is-archived-field">
        <strong>В архиве</strong>
      </label>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </div>
</div>

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Клиенты</h2>
            </div>
            <p class="pull-right">
                <a
                    class="btn btn-success"
                    href="{{ route('clients.create') }}"
                >Добавить клиента</a>
            </p>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <clients></clients>
@endsection

resources/views/clients/payments.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-lg-12 mb-3">
      <div class="pull-left">
        <h2>Клиент "{{ $client->name }}"</h2>
      </div>

      <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('clients.index') }}">
          <v-icon name='arrow-left'></v-icon>
        &nbsp;&nbsp;Назад
        </a>
        <a class="btn btn-primary" href="{{ route('clients.edit', $client->id) }}">
          <v-icon name='pen'></v-icon>
        </a>
      </div>
    </div>
  </div>

  @include('clients.payments__client-details')
  @include('clients.payments__payments')
@endsection

resources/views/clients/payments__client-details.blade.php
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <strong>Телефон:</strong>
      {{ $client->phone }}
    </div>
  </div>

  <div class="col-md-12">
    <div class="form-group">
      <strong>Адрес:</strong>
      {{ $client->address }}
    </div>
  </div>

  <div class="col-md-12">
    <div class="form-group">
      <strong>Прайслист:</strong>
      {{ $client->pricelist ? $client->pricelist->name : '<Не указан>' }}
    </div>
  </div>
</div>

resources/views/clients/payments__payment-form.blade.php
{{-- !!! Комментим это, потому что не работает --}}
{{--<p class="pull-right">--}}
{{--  <a--}}
{{--    :class="globalVar.showAddingPayment ? 'btn btn-primary' : 'btn btn-success'"--}}
{{--    href="javascript: void(0)"--}}
{{--    @click="globalVar.showAddingPayment = !globalVar.showAddingPayment"--}}
{{--  >--}}
{{--    <template v-if="globalVar.showAddingPayment">Скрыть добавление оплаты</template>--}}
{{--    <template v-else>@lang('payments.buttons.add')</template>--}}
{{--  </a>--}}
{{--</p>--}}

{!! Form::open(['route' => 'payments.store', 'method' => 'POST']) !!}
{{--    <div--}}
{{--      v-if="globalVar.showAddingPayment"--}}
{{--      class="row border pt-3 pb-2 mb-2 b-payment-adding"--}}
{{--    >--}}
{{--        <div class="col-md-12">--}}
{{--            <h3>Добавление оплаты</h3>--}}
{{--        </div>--}}

{{--        <div class="col-md-6">--}}
{{--            <div class="form-group">--}}
{{--                <strong>@lang('payments.fields.date'):</strong>--}}
{{--                {{ Form::date('date', new \DateTime(), ['class' => 'form-control']) }}--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <div class="col-md-6">--}}
{{--            <div class="form-group">--}}
{{--                <strong>@lang('payments.fields.amount'):</strong>--}}
{{--                <float-number-view--}}
{{--                    class="form-control"--}}
{{--                    name="amount"--}}
{{--                    required="required"--}}
{{--                ></float-number-view>--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <div class="col-md-12">--}}
{{--            <div class="form-group">--}}
{{--                <strong>@lang('payments.fields.comment'):</strong>--}}
{{--                {!! Form::text('comment', null, ['placeholder' => '', 'class' => 'form-control']) !!}--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <div class="col-md-12 text-center">--}}
{{--            <button type="submit" class="btn btn-primary">@lang('elements.buttons.save')</button>--}}
{{--        </div>--}}
{{--    </div>--}}

    {!! Form::hidden('client_id', $client->id) !!}
{!! Form::close() !!}

resources/views/clients/payments__payments.blade.php
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h3>Оплаты</h3>
    </div>

    @include('clients.payments__payment-form')
  </div>

  <table class="table table-striped">
    <thead>
    <tr>
      {{--<th>#</th>--}}
      <th>№</th>
      <th>Дата</th>
      <th>Сумма</th>
      <th>Комментарий</th>
      <th style="width: 120px;">Действие</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($client->payments as $i => $payment)
      <tr>
        {{--                    <td>{{ ++$i }}</td>--}}
        <td>{{ $payment->id }}</td>
        <td>{{ date("d.m.Y", strtotime($payment->date)) }}</td>
        <td>{{ fineNumber($payment->amount, false) . ' руб.' }}</td>
        <td>{{ $payment->comment }}</td>

        <td>
          <a class="btn btn-primary" href="{{ route('payments.edit', $payment->id) }}">
            <v-icon name='pen'></v-icon>
          </a>
          {!! Form::open([
               'method' => 'DELETE',
               'route'  => ['payments.destroy', $payment->id],
               'style'  => 'display: inline'
          ]) !!}
          <button onclick="if (confirm('Хотите удалить этот элемент?')) this.form.submit(); else return false;"
                  class="btn btn-danger">
            <v-icon name='trash'></v-icon>
          </button>
          {!! Form::close() !!}
        </td>
      </tr>
    @endforeach

    @if (!count($client->payments))
      <tr>
        <td colspan="5">Оплат нет</td>
      </tr>
    @endif
    </tbody>
  </table>
</div>

resources/views/clients/show.blade.php
@extends('layouts.app')

@section('content')
    {{--<div class="row">--}}
        {{--<div class="col-lg-12 margin-tb">--}}
            {{--<div class="pull-left">--}}
                {{--<h2>Show Client</h2>--}}
            {{--</div>--}}
            {{--<div class="pull-right">--}}
                {{--<a class="btn btn-primary" href="{{ route('clients.index') }}">@lang('elements.buttons.back')</a>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}

    {{--<div class="row">--}}
        {{--<div class="col-md-12">--}}
            {{--<div class="form-group">--}}
                {{--<strong>Title:</strong>--}}
                {{--{{ $article->title }}--}}
            {{--</div>--}}
        {{--</div>--}}
        {{--<div class="col-md-12">--}}
            {{--<div class="form-group">--}}
                {{--<strong>Body:</strong>--}}
                {{--{{ $article->body }}--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
@endsection