routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'register' => false,
]);

Route::get('/home', function () {
    return redirect('/');
});
Route::post('/login-only-with-password', 'Auth\LoginController@loginOnlyWithPassword')->middleware('guest');

Route::get('/control', 'Auth\ControlModeController@showControlPage')->name('control');
Route::get('/unset-control', 'Auth\ControlModeController@unsetControlMode')->name('unset-control');
Route::post('/set-control', 'Auth\ControlModeController@setControlMode')->name('set-control');

Route::middleware(['auth', 'locale'])->group(function () {
    // --- Clients
    Route::get('/api/clients', 'Api\ClientController@list');
    Route::post('/api/clients', 'Api\ClientController@list');
    Route::get('/clients/debts', 'ClientController@debts')->name('clients.debts');
    Route::resource('clients', 'ClientController');
    Route::get('/clients/{id}/payments', 'ClientController@payments')->name('clients.payments');

    // --- Invoices
    // TODO: should refactor
    Route::get('/api/invoices', 'Api\InvoiceController@list');
    Route::get('/api/invoices/{id}', 'Api\InvoiceController@show');
    Route::get('/api/invoices/{id}/invoice-products', 'Api\InvoiceProductController@getInvoiceProductsByInvoiceId');
    Route::resource('invoices', 'InvoiceController');
    Route::get('/api/invoices/{invoice}/download', 'Api\InvoiceController@download')->name('api.invoices.download');

    // --- Payments
    Route::post('/api/payments/store', 'Api\PaymentController@store');
    Route::delete('/api/payments/{id}', 'Api\PaymentController@destroy');
    Route::resource('payments', 'PaymentController');

    // --- Supplier Invoices
    Route::get('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@show');
    Route::post('/api/supplier-invoices/store', 'Api\SupplierInvoiceController@store');
    Route::patch('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@update');
    Route::delete('/api/supplier-invoices/{id}', 'Api\SupplierInvoiceController@destroy');
    Route::get('/supplier-invoices{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Products
    Route::resource('products', 'ProductController')->names('products');
    Route::prefix('api')->name('api.')->group(function () {
        Route::prefix('products')->name('products.')->group(function () {
            Route::get('/', 'Api\ProductController@list')->name('list');
            // TODO: should refactor to /invoice-prices
            Route::get('/prices', 'Api\ProductController@getProductsWithInvoicePrices')->name('get-products-with-invoice-prices');
            Route::get('/supply-prices', 'Api\ProductController@getProductsWithSupplyPrices')->name('get-products-with-supply-prices');
            // TODO: should refactor
            Route::get('/barcodes', 'Api\ProductController@getAllWithBarcode')->name('barcodes');
        });
    });

    // --- Client Price lists
    Route::prefix('api')->name('api.')->group(function () {
        Route::get('/client-pricelists', 'Api\ClientPricelistController@list')->name('client-pricelist.index');
        Route::get('/client-pricelists/{id}', 'Api\ClientPricelistController@show')->name('client-pricelist.show');
        Route::post('/client-pricelists/{pricelist}/duplicate', 'Api\ClientPricelistController@duplicate')->name('client-pricelist.duplicate');
        Route::delete('/client-pricelists/{id}', 'Api\ClientPricelistController@destroy')->name('client-pricelist.destroy');
    });
    Route::resource('client-pricelists', 'ClientPricelistController');
    Route::get('/client-pricelists', function () {
        return view('default');
    })->where('all', '.*')->name('client-pricelists.index');
    Route::get('/client-pricelists/{id}/duplicate', function () {
        return view('default');
    })->where('all', '.*');

    // --- Supplier Price lists
    Route::get('/api/supplier-pricelists', 'Api\SupplierPricelistController@list');
    Route::delete('/api/supplier-pricelists/{id}', 'Api\SupplierPricelistController@destroy');
    Route::resource('supplier-pricelists', 'SupplierPricelistController');

    // --- Reports
    Route::get('/api/reports/by-client-payments', 'Api\ReportController@byPayments');
    Route::post('/api/reports/by-products', 'Api\ReportController@byProducts');
    Route::post('/api/reports/products-moving', 'Api\ReportController@productsMoving')->middleware('control-mode');
    Route::get('/api/reports/revision-by-suppliers', 'Api\ReportController@revisionBySuppliers')->middleware('control-mode');
    Route::get('/api/reports/by-supplies', 'Api\ReportController@bySupplies')->middleware('control-mode');
    Route::get('/reports/by-products', function () {
        return view('reports.by-products');
    })->name('reports.by-products');
    Route::get('/reports/products-moving', function () {
        return view('reports.products-moving');
    })->middleware('control-mode')->name('reports.products-moving');
    Route::get('/reports/by-client-payments', function () {
        return view('default');
    })->name('reports.by-payments');
    Route::get('/reports/revision-by-suppliers', function () {
        return view('default');
    })->middleware('control-mode')->name('reports.by-suppliers');
    Route::get('/reports/by-supplies', function () {
        return view('default');
    })->middleware('control-mode')->name('reports.by-supplies');

    // --- Revisions
    Route::post('/api/revision/get-supplies-and-invoices', 'Api\RevisionController@getSuppliesAndInvoices')->middleware('control-mode');
    Route::get('/revisions', 'RevisionController@index')->middleware(['locale', 'control-mode'])->name('revisions');
    //Route::get('/stocktaking', 'RevisionController@stocktaking')->middleware('locale');

    // --- Suppliers
    Route::get('/api/suppliers', 'Api\SupplierController@index');
    Route::post('/api/suppliers', 'Api\SupplierController@store');
    Route::get('/api/suppliers/{id}', 'Api\SupplierController@show');
    Route::patch('/api/suppliers/{id}', 'Api\SupplierController@update');
    Route::delete('/api/suppliers/{id}', 'Api\SupplierController@destroy');
    Route::get('/suppliers{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Supplies
    Route::post('/api/supplies', 'Api\SupplyController@store');
    Route::get('/api/supplies/{id}', 'Api\SupplyController@show');
    // patch не работает с form-data в laravel
    Route::post('/api/supplies/{id}', 'Api\SupplyController@update');
    Route::delete('/api/supplies/{id}', 'Api\SupplyController@destroy');
    Route::get('/api/supplies/{id}/supply-products', 'Api\SupplyProductController@getSupplyProductsBySupplyId');
    Route::get('/supplies{all}', function () {
        return view('default');
    })->where('all', '.*');
//    Route::apiResource('activity', 'Api\ActivityController')->names('activity');

    // --- Orders
    Route::prefix('api')->name('api.')->group(function () {
        Route::apiResource('orders', 'Api\OrderController')->names('order');
    });
    Route::get('/orders', function () {
        return view('default');
    })->name('orders.index');
    Route::get('/orders{all}', function () {
        return view('default');
    })->where('all', '.*');

    // --- Logs
    Route::get('/logs/login', function () {
        return view('default');
    })->middleware('control-mode')->name('logs.login');

    // --- Settings
    Route::prefix('settings')
        ->name('settings.')
        ->middleware('control-mode')
        ->group(function () {
            Route::get('/', 'SettingsController@index')->name('index');
            Route::get('/euro-price/edit', function () {
                return view('default');
            })->name('euro-price.edit');
        });
    Route::prefix('api/settings')
         ->name('api.settings.')
         ->middleware('control-mode')
         ->group(function () {
             Route::get('/', 'Api\SettingController@index')->name('index');
             Route::post('/', 'Api\SettingController@store')->name('store');
             Route::patch('/', 'Api\SettingController@update')->name('update');
             Route::delete('/', 'Api\SettingController@destroy')->name('destroy');
         });
});

Route::apiResource('/api/activity', 'Api\ActivityController')->names('activity');

//Route::resource('supplies', 'SupplyController');

Route::permanentRedirect('/', \App\Models\User::HOME_URL);

//Route::get('/', 'RevisioController@index')->middleware('locale');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Stock') }}</title>

  <!-- Scripts -->
  <script src="{{ mix('js/app.js') }}" defer></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

  <!-- Styles -->
  <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div
  class="b-app"

  @if(Auth::user())
    id="app"
  @endif
>
  <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
      <div class="navbar-nav mr-auto">
        <div class="nav-item">
          @if (\App\Models\ControlMode::checkModeIsControl())
            <a class="nav-link" href="{{ route('unset-control') }}">-S</a>
          @else
            <a class="nav-link" href="{{ route('control') }}">S</a>
          @endif
        </div>
      </div>

      <a class="navbar-brand" href="{{ \App\Models\User::HOME_URL }}">
        {{ config('app.name', 'Stock') }}
      </a>

      <button
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="{{ __('Toggle navigation') }}"
        class="navbar-toggler"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        type="button"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        @auth
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">
            @if (\App\Models\ControlMode::checkModeIsControl())
              {{-- Сверка --}}
              <li class="nav-item">
                <a class="nav-link" href="/revisions">Сверка</a>
              </li>

              {{-- Склад --}}
              <li class="nav-item">
                <a class="nav-link" href="{{ route('products.index') }}">Склад</a>
              </li>
            @endif

            {{-- Поставщики --}}
            <li class="nav-item">
              <a class="nav-link" href="/suppliers">Поставщики</a>
            </li>

            {{-- Клиенты --}}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="javascript: void(0);"
                id="navbarReportsDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Клиенты
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarReportsDropdown">
                <a class="dropdown-item" href="{{ route('clients.index') }}">Все клиенты</a>
                <a class="dropdown-item" href="{{ route('clients.debts') }}">Долги клиентов</a>
              </div>
            </li>

            {{-- Счета --}}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="javascript: void(0);"
                id="navbarReportsDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Счета и заказы
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarReportsDropdown">
                <a class="dropdown-item" href="{{ route('invoices.index') }}">Счета</a>
                <a class="dropdown-item" href="{{ route('orders.index') }}">Заказы</a>
              </div>
            </li>

            {{-- Прайс-листы --}}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="javascript: void(0);"
                id="navbarReportsDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Прайс-листы
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarReportsDropdown">
                <a
                  class="dropdown-item"
                  href="{{ route('supplier-pricelists.index') }}"
                >Прайс-листы поставщиков</a>
                <a
                  class="dropdown-item"
                  href="{{ route('client-pricelists.index') }}"
                >Прайс-листы клиентов</a>
              </div>
            </li>

            {{-- Отчеты --}}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="javascript: void(0);"
                id="navbarReportsDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Отчеты
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarReportsDropdown">
                <a class="dropdown-item" href="/reports/by-products">Отчет по товарам</a>
                <a class="dropdown-item" href="/reports/by-client-payments">Платежи клиентов</a>

                @if (\App\Models\ControlMode::checkModeIsControl())
                  <a class="dropdown-item" href="/reports/products-moving">Отчет по продажам</a>

                  <div class="dropdown-divider"></div>

                  <a class="dropdown-item" href="/reports/revision-by-suppliers">Сверка поставщиков</a>
                  <a class="dropdown-item" href="/reports/by-supplies">Грузить на склад</a>
                @endif
              </div>
            </li>
          </ul>
        @endauth

        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
          <!-- Authentication Links -->
          @guest
            <li class="nav-item">
              <a class="nav-link" href="{{ route('login') }}">Вход</a>
            </li>
            {{--<li class="nav-item">--}}
            {{--@if (Route::has('register'))--}}
            {{--<a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
            {{--@endif--}}
            {{--</li>--}}
          @else
            <li class="nav-item dropdown">
              <a
                aria-haspopup="true"
                aria-expanded="false"
                data-toggle="dropdown"
                href="javascript: void(0);"
                id="navbarDropdown"
                role="button"
                class="nav-link dropdown-toggle"
              >
                S <span class="caret"></span>
              </a>

              <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
                @if (\App\Models\ControlMode::checkModeIsControl())
                  <a
                    href="{{ route('settings.index') }}"
                    class="dropdown-item"
                  >
                    Настройки
                  </a>
                  <a
                    href="{{ route('logs.login') }}"
                    class="dropdown-item"
                  >
                    История входов
                  </a>
                @endif
                <a
                  href="{{ route('logout') }}"
                  class="dropdown-item"
                  onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                >
                  Выход
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
              </div>
            </li>
          @endguest
        </ul>
      </div>
    </div>
  </nav>

  <main class="container py-4">
    @yield('content')
  </main>
</div>
</body>
</html>

resources/views/layouts/pdf.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>{{ config('app.name', 'Stock') }}</title>
  <script src="{{ mix('js/app.js') }}" defer></script>
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
  <link href="{{ mix('css/app.css') }}" rel="stylesheet">
  <style>
    @font-face {
      font-family: "DejaVu Sans";
      font-style: normal;
      font-weight: 400;
      src: url("/fonts/dejavu-sans/DejaVuSans.ttf");
      /* IE9 Compat Modes */
      src: local("DejaVu Sans"),
      local("DejaVu Sans"),
      url("/fonts/dejavu-sans/DejaVuSans.ttf") format("truetype");
    }

    body {
      font-family: "DejaVu Sans", sans-serif;
      font-size: 13px;
    }

    table {
      border-spacing: 0;
      border-collapse: collapse;
    }

    table td {
      vertical-align: top;
    }

    table td,
    table th {
      border: solid 1px #444;
      padding: 0.5rem;
    }
  </style>
</head>
<body>
<div
  class="b-app"
  @if(Auth::user()) id="app" @endif
>
  <h1>{{ config('app.name', 'Stock') }}</h1>
  @yield('content')
</div>
</body>
</html>